// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNewProject(arg1:string):Promise<string>;

export function CreateUser(arg1:string):Promise<string>;

export function GetUser():Promise<main.User>;

export function Greet(arg1:string):Promise<string>;
