// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewProject(arg1) {
  return window['go']['main']['App']['CreateNewProject'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
